### ISSUE TITLE
[HAS-FIX] CDN issues loading assets 

### ISSUE THREAD

**Issue by FabioGuin** [Laravel-Backpack/basset#119] opened 2024-04-12 07:02 UTC
Apparently CloudFlare today does not allow additional parameters in the URL, for example:
https://unpkg.com/select2@4.0.13/dist/css/select2.min.css?f87fe3cd3b0b

While it works https://unpkg.com/select2@4.0.13/dist/css/select2.min.css

This is blocking the work.

**Comment by pxpm** [comment] 2024-04-12 08:31
Hey @FabioGuin 

Thanks for the report. 

We are tracking this issue here: https://github.com/Laravel-Backpack/community-forum/issues/928

**Comment by rich-williamson** [comment] 2024-04-12 11:05
This affects anyone using Backpack. If you are using backpack in a production environment don't do a `php artisan basset:clear` as you'll break your production site.

You can set `dev_mode` to false in your `config/backpack/basset.php` to load the assets from the local file system but this of course only works if you have previously downloaded assets successfully.

**Comment by dauvray** [comment] 2024-04-12 11:23
the problem is always here with 1.3.1

![image](https://github.com/Laravel-Backpack/basset/assets/3491828/37afcfc6-8b3b-4d7c-8c95-87969b3c382f)

**Comment by pxpm** [comment] 2024-04-12 11:27
@dauvray can you do `php artisan basset:clear && php artisan basset:cache` ? 

Let me know the output. 

Cheers

**Comment by pxpm** [comment] 2024-04-12 11:29
To avoid having duplicate conversations about the same subject, I am closing this issue in favor of https://github.com/Laravel-Backpack/community-forum/issues/928

Please post any feedback you need there. 

@dauvray I opened an issue for your problem. Please let's move the conversation over there.

**Comment by dauvray** [comment] 2024-04-12 11:29
it works if i put BASSET_DEV_MODE=false in my .env.
if i remote it, it fails

**Closed by pxpm** 2024-04-12 11:29 UTC
Labels: Priority: MUST
